server:
  port: 9060

spring:
  application:
    name: authcenter
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:4306/nsinformation?useUnicode=true&characterEncoding=utf-8
    username: nsinformation
    password: ***
    druid:
      driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
    port: 6489
    password: 5XqAmP9EsSG03ahC9Fjg
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    ##续约更新时间间隔设置5秒，m默认30s
    lease-renewal-interval-in-seconds: 1
    ##续约到期时间10秒，默认是90秒
    lease-expiration-duration-in-seconds: 2
  client:
      service-url:
        defaultZone: http://mss-eureka:9010/eureka/
logging:
  config: classpath:logback.xml
  level:
    org:
      springframework:
        web: info
###feign 默认关闭熔断，请看HystrixFeignConfiguration
feign:
  hystrix:
    enabled: false
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  ActiveConnectionsLimit: 2147483647